name: Esteira de testes
run-name: ${{ github.actor }} is testing out 🚀
on: 
  push:
    branches:
      - 'feature**'
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Build with gradle
        run:  gradle build -x test    
  Execute_Unit_Tests:
    needs: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Unit Tests
        run:  gradle test
  Execute_Integrations_Tests:
    needs: Execute_Unit_Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Integration Tests
        run:  gradle integrationTest     
  Code Coverage Report:
    needs: Execute_Unit_Tests
    runs-on: ubuntu-latest
    steps:
      - uses: irongut/CodeCoverageSummary@v1.3.0
      - with:
          filename: src/test/resources/report/coverage/coverage-cobertura.xml
          badge: true
          fail_below_min: true
          format: markdown
          hide_branch_rate: false
          hide_complexity: true
          indicators: true
          output: both
          thresholds: '60 80'
